### ISSUE TITLE
Add Command to Seed Migrations Table

### ISSUE THREAD

**Issue by techgerm** [maroux/python-spanner-orm#16]
**Consider the following scenario:**
* A developer wants to stand up a development/staging Spanner DB
* Developer creates DB with the latest models from a `master` branch
* In order to continue development, the developer would need to make sure that all migrations are marked as true in the new dev/staging database to ensure none of the current migrations in the repo are executed.

**Proposed solution:**
* `MigrationExecutor` should have a `seed_migrations_table` function that seeds the migrations table with all the current migrations in the repo.

**Comment by maroux** [comment]
I like django's `--fake` flag here, which can be used regardless of seeding - e.g. you applied the migration manually for some reason, you can `migrate foobar --fake` later so migrations table matches reality.

**Comment by techgerm** [comment]
works for me as well 👍
